/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import Clases.Contacto;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.PreparedStatement;


/**
 *
 * @author Gustavo y Cesar
 */
public class VistaContactos extends javax.swing.JFrame {

    Conexion con1 = new Conexion();
    Connection conet;
    Statement st;
    ResultSet rs;
    private TableRowSorter trsfiltro;
    private String filtro;
    TableRowSorter trs;

    ArrayList<Contacto> contactos;
    DefaultTableModel modelo;
    static int codigo = 1;

    public VistaContactos() {

        initComponents();
        contactos = new ArrayList();
        modelo = new DefaultTableModel();

        // Columnas de la lista
        modelo.addColumn("CODIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("CORREO");
        modelo.addColumn("EMPRESA");
        modelo.addColumn("NUMERO");

        trs = new TableRowSorter<>(modelo);
        Tabla.setRowSorter(trs);

        mostrarDatos();
        consultar();

    }

    public void jtable() {
        initComponents();
        consultar();

    }

    public void mostrarDatos() {
        modelo.setNumRows(contactos.size());
        for (var i = 0; i < contactos.size(); i++) {

            modelo.setValueAt(contactos.get(i).getNombre(), i, 1);
            modelo.setValueAt(contactos.get(i).getApellido(), i, 2);
            modelo.setValueAt(contactos.get(i).getCorreo(), i, 3);
            modelo.setValueAt(contactos.get(i).getEmpresa(), i, 4);
            modelo.setValueAt(contactos.get(i).getTelefono(), i, 5);

        }

        Tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlMiAgenda = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        tfempresa = new javax.swing.JTextField();
        btguardar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jlEmpresa = new javax.swing.JLabel();
        tfapellido = new javax.swing.JTextField();
        jlCorreo1 = new javax.swing.JLabel();
        tfcorreo = new javax.swing.JTextField();
        jlBuscar = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        tfBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlMiAgenda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlMiAgenda.setForeground(new java.awt.Color(0, 0, 0));
        jlMiAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMiAgenda.setText("Mi agenda");

        jlNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(0, 0, 0));
        jlNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNombre.setText("Nombre:");

        jlApellido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(0, 0, 0));
        jlApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlApellido.setText("Apellido:");

        tfnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tfempresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });

        bteliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        btmodificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btmodificar.setText("Modificar");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jlEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        jlEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEmpresa.setText("Empresa:");

        tfapellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlCorreo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlCorreo1.setForeground(new java.awt.Color(0, 0, 0));
        jlCorreo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCorreo1.setText("Correo:");

        tfcorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlBuscar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jlBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBuscar.setText("Buscar:");

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlNumero.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlNumero.setForeground(new java.awt.Color(0, 0, 0));
        jlNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNumero.setText("Numero:");

        tfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarActionPerformed(evt);
            }
        });
        tfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlNombre)
                                            .addComponent(jlApellido))
                                        .addComponent(jlCorreo1)
                                        .addComponent(jlEmpresa, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlBuscar)
                                        .addComponent(jlNumero)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfnombre)
                                    .addComponent(tfapellido)
                                    .addComponent(tfempresa)
                                    .addComponent(tfcorreo)
                                    .addComponent(jlMiAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(tfTelefono)
                                    .addComponent(tfBuscar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btguardar)
                                .addGap(18, 18, 18)
                                .addComponent(bteliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btmodificar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlMiAgenda)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(tfapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCorreo1)
                    .addComponent(tfcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEmpresa))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumero))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBuscar)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btguardar)
                    .addComponent(bteliminar)
                    .addComponent(btmodificar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Boton guardar
    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        accionBotonGuardar();


    }//GEN-LAST:event_btguardarActionPerformed

    public void accionBotonGuardar() {

        mostrarDatos();
        agregarBD();
        consultar();

    }

    public void agregarBD() {
    if (!tfnombre.getText().isEmpty() && !tfapellido.getText().isEmpty() && !tfTelefono.getText().isEmpty()) {
        String nom = tfnombre.getText();
        String ape = tfapellido.getText();
        String cor = tfcorreo.getText();
        String emp = tfempresa.getText();
        String num = tfTelefono.getText();

        // Verificar si el número de teléfono tiene exactamente 10 dígitos
        if (num.length() != 10) {
            JOptionPane.showMessageDialog(null, "El número de teléfono debe tener exactamente 10 dígitos");
            return; // Salir del método si el número no tiene 10 dígitos
        }

        try {
            // Verificar si el número de teléfono ya existe en la base de datos
            String sqlCheckExistence = "SELECT COUNT(*) FROM agenda WHERE numero = ?";
            conet = con1.getConnection();
            PreparedStatement pstCheckExistence = conet.prepareStatement(sqlCheckExistence);
            pstCheckExistence.setString(1, num);
            ResultSet rsCheckExistence = pstCheckExistence.executeQuery();
            rsCheckExistence.next();
            int count = rsCheckExistence.getInt(1);
            if (count > 0) {
                JOptionPane.showMessageDialog(null, "El número de teléfono ya está en la agenda");
                return; // Salir del método si el número ya existe
            }

            // Insertar el nuevo contacto en la base de datos
            String sql = "INSERT INTO agenda(nombre, apellido, correo, empresa, numero) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = conet.prepareStatement(sql);
            pst.setString(1, nom);
            pst.setString(2, ape);
            pst.setString(3, cor);
            pst.setString(4, emp);
            pst.setString(5, num);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Nuevos datos agregados");

            limpiarCamposTexto();

        } catch (HeadlessException | SQLException e) {
            // Manejar las excepciones
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al agregar datos: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Ingrese los datos que se piden");
    }
}


    // Boton eliminar
    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        limpiarRegistro();

    }//GEN-LAST:event_bteliminarActionPerformed

    public void limpiarRegistro() {
        int filaSeleccionada = Tabla.getSelectedRow();

        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecciona el registro que quieres eliminar");
        } else {
            int idRegistro = (int) Tabla.getValueAt(filaSeleccionada, 0);
            String sqlDelete = "DELETE FROM agenda WHERE id = " + idRegistro;

            try {
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sqlDelete);  // Eliminar el registro seleccionado

                // Reiniciar el contador de ID en la tabla agenda
                String sqlResetAutoIncrement = "ALTER TABLE agenda AUTO_INCREMENT = 1";
                st.executeUpdate(sqlResetAutoIncrement);

                // Actualizar la tabla después de borrar los registros
                modelo = (DefaultTableModel) Tabla.getModel();
                modelo.setRowCount(0);  // Eliminar todas las filas de la tabla
                Tabla.setModel(modelo);

                consultar();

            } catch (SQLException e) {
            }
        }

    }

    // Boton modificar
    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed

        accionBotonModificar();
    }//GEN-LAST:event_btmodificarActionPerformed

  // Método accionBotonModificar
public void accionBotonModificar() {
    if (Tabla.getSelectedRow() < 0) {
        JOptionPane.showMessageDialog(null, "Selecciona el registro que quieres modificar");
    } else {
        int filaSeleccionada = Tabla.getSelectedRow();
        // Obtener los valores de la fila seleccionada
        String nombre = Tabla.getValueAt(filaSeleccionada, 1).toString();
        String apellido = Tabla.getValueAt(filaSeleccionada, 2).toString();
        String correo = Tabla.getValueAt(filaSeleccionada, 3).toString();
        String empresa = Tabla.getValueAt(filaSeleccionada, 4).toString();
        String numero = Tabla.getValueAt(filaSeleccionada, 5).toString();
        
        // Modificar los datos directamente en los campos de texto
        tfnombre.setText(nombre);
        tfapellido.setText(apellido);
        tfcorreo.setText(correo);
        tfempresa.setText(empresa);
        tfTelefono.setText(numero);

        // Manejar la modificación en el mismo método
        btguardar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!tfnombre.getText().isEmpty() && !tfapellido.getText().isEmpty() && !tfTelefono.getText().isEmpty()) {
                    String nom = tfnombre.getText();
                    String ape = tfapellido.getText();
                    String cor = tfcorreo.getText();
                    String emp = tfempresa.getText();
                    String num = tfTelefono.getText();

                    // Verificar si el número de teléfono tiene exactamente 10 dígitos
                    if (num.length() != 10) {
                        JOptionPane.showMessageDialog(null, "El número de teléfono debe tener exactamente 10 dígitos");
                        return; // Salir del método si el número no tiene 10 dígitos
                    }

                    try {
                        // Modificar los datos en la base de datos
                        int idRegistro = (int) Tabla.getValueAt(filaSeleccionada, 0);
                        String sqlUpdate = "UPDATE agenda SET nombre = ?, apellido = ?, correo = ?, empresa = ?, numero = ? WHERE id = ?";
                        conet = con1.getConnection();
                        PreparedStatement pst = conet.prepareStatement(sqlUpdate);
                        pst.setString(1, nom);
                        pst.setString(2, ape);
                        pst.setString(3, cor);
                        pst.setString(4, emp);
                        pst.setString(5, num);
                        pst.setInt(6, idRegistro);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Datos modificados exitosamente");

                        // Limpiar los campos después de modificar los datos
                        limpiarCamposTexto();

                    } catch (HeadlessException | SQLException ex) {
                        // Manejar las excepciones
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error al modificar datos: " + ex.getMessage());
                    }
                } 
            }
        });
    }
}







    
   
          
    // Buscar
    private void tfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarActionPerformed
        
    }//GEN-LAST:event_tfBuscarActionPerformed

    private void tfBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarKeyTyped
        buscar();
    }//GEN-LAST:event_tfBuscarKeyTyped

    public void buscar() {
        String texto = tfBuscar.getText().trim();

        RowFilter<DefaultTableModel, Object> filtro = RowFilter.regexFilter("(?i)" + texto);

        trs.setRowFilter(filtro);

    }

    

    public void consultar() {
        String sql = "select * from agenda";

        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] agenda = new Object[6];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                agenda[0] = rs.getInt("id");
                agenda[1] = rs.getString("nombre");
                agenda[2] = rs.getString("apellido");
                agenda[3] = rs.getString("correo");
                agenda[4] = rs.getString("empresa");
                agenda[5] = rs.getString("numero");

                modelo.addRow(agenda);

            }
            Tabla.setModel(modelo);

        } catch (SQLException e) {
        }

    }

    public void limpiarCamposTexto() {
        tfnombre.setText("");
        tfapellido.setText("");
        tfcorreo.setText("");
        tfempresa.setText("");
        tfTelefono.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaContactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btmodificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlCorreo1;
    private javax.swing.JLabel jlEmpresa;
    private javax.swing.JLabel jlMiAgenda;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfapellido;
    private javax.swing.JTextField tfcorreo;
    private javax.swing.JTextField tfempresa;
    private javax.swing.JTextField tfnombre;
    // End of variables declaration//GEN-END:variables
}
